### ISSUE TITLE
Style Optimisation not working

### ISSUE THREAD

**Issue by swarmukhdefault** [A-l-y-l-e/Alyle-UI#194]
# :beetle: Bug report

### Describe the bug
Style Optimisation not working

### Minimal Reproduction
Run `yarn lyl src`

### Exception or Error
<pre><code>
/home/erp-app/node_modules/@alyle/ui/style-compiler/main.js:42
    console.log(chalk_1.default.bold.blueBright(`Directory: ${directory}`));
                                ^

TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (/home/erp-app/node_modules/@alyle/ui/style-compiler/main.js:42:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
</code></pre>

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
`v13.2.2`

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 14.1.1
Node: 14.20.0
Package Manager: yarn 1.22.5
OS: linux x64

Angular: 14.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.1
@angular-devkit/build-angular   14.1.1
@angular-devkit/core            14.1.1
@angular-devkit/schematics      14.1.1
@angular/cdk                    13.3.9
@schematics/angular             14.1.1
ng-packagr                      14.1.0
rxjs                            7.5.6
typescript                      4.7.4

</code></pre>

**Comment by swarmukhdefault** [comment]
@Enlcxx Any updates on this?

**Comment by Enlcxx** [comment]
@swarmukhdefault try if it works with version 16 of node js

**Comment by swarmukhdefault** [comment]
Nope, still the same issue (updated node to `18.12.1 LTS`):

```bash
/home/erp-app/node_modules/@alyle/ui/style-compiler/main.js:42
    console.log(chalk_1.default.bold.blueBright(`Directory: ${directory}`));
                                ^

TypeError: Cannot read properties of undefined (reading 'bold')
    at Object.<anonymous> (/home/erp-app/node_modules/@alyle/ui/style-compiler/main.js:42:33)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
error Command failed with exit code 1.
```
